### ISSUE TITLE
    cv2.namedWindow(self.window_name) cv2.error: /io/opencv/modules/highgui/src/window.cpp:565: error: (-2) 

### ISSUE THREAD

**Issue by stjordanis** [yosinski/deep-visualization-toolbox#101]
I have managed to run deep-visualization-toolbox in the past, but now it fails to do so. Is it only compatible with opencv 2.4? I use opencv 3.1 now

here is the complete error log I get:

Running toolbox. Push h for help or q to quit.

OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file /io/opencv/modules/highgui/src/window.cpp, line 565
Traceback (most recent call last):
  File "/media/steliox/WIN/deep-visualization-toolbox/run_toolbox.py", line 33, in <module>
    main()
  File "/media/steliox/WIN/deep-visualization-toolbox/run_toolbox.py", line 28, in main
    lv.run_loop()
  File "/media/steliox/WIN/deep-visualization-toolbox/live_vis.py", line 121, in run_loop
    self.init_window()
  File "/media/steliox/WIN/deep-visualization-toolbox/live_vis.py", line 84, in init_window
    cv2.namedWindow(self.window_name)
cv2.error: /io/opencv/modules/highgui/src/window.cpp:565: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

**Comment by phdshliang** [comment]
this maybe helpful.
`pip uninstall opencv-python
sudo apt-get install libgtk-3-dev `
