### ISSUE TITLE
ImportError: ... _fblas.so, 2): Symbol not found: ___addtf3

### ISSUE THREAD

**Issue by genemiller** [yosinski/deep-visualization-toolbox#104]
Error occurred when importing LiveVis from live_vis:
```
Genes-MacBook-Pro:deep-visualization-toolbox gene$ ./run_toolbox.py
Traceback (most recent call last):
  File "./run_toolbox.py", line 4, in <module>
    from live_vis import LiveVis
  File "/Users/gene/GitHub/deep-visualization-toolbox/live_vis.py", line 18, in <module>
    from image_misc import cv2_imshow_rgb, FormattedString, cv2_typeset_text, to_255
  File "/Users/gene/GitHub/deep-visualization-toolbox/image_misc.py", line 6, in <module>
    import skimage.io
  File "/Users/gene/anaconda/lib/python2.7/site-packages/skimage/io/__init__.py", line 11, in <module>
    from ._io import *
  File "/Users/gene/anaconda/lib/python2.7/site-packages/skimage/io/_io.py", line 7, in <module>
    from ..color import rgb2grey
  File "/Users/gene/anaconda/lib/python2.7/site-packages/skimage/color/__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "/Users/gene/anaconda/lib/python2.7/site-packages/skimage/color/colorconv.py", line 58, in <module>
    from scipy import linalg
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 175, in <module>
    from .misc import *
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/opt/gcc/lib/gcc/6/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/6/libquadmath.0.dylib
```

I installed everything per instructions below.

Python Version:
```
  Python 2.7.11 |Anaconda 2.3.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
  [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
```
Added following item to make cv2 accessible:
```
$ mkdir -p /Users/gene/.local/lib/python2.7/site-packages
$ echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/gene/.local/lib/python2.7/site-packages/homebrew.pth
```

**Comment by genemiller** [comment]
Problem solved.
Removing and re-installing the scipy fixed the issue.
(see https://github.com/scipy/scipy/issues/5093)

**Comment by genemiller** [comment]
Problem solved.
Removing and re-installing the scipy fixed the issue.
(see scipy/scipy#5093)

**Comment by rislam** [comment]
I am getting the same issue with gcc 8. And the solution suggested is not working.

> Symbol not found: ___addtf3
>   Referenced from: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
>
