### ISSUE TITLE
live_vis.py problems expected 2 for FC or 4 for conv layer

### ISSUE THREAD

**Issue by buaa-luzhi** [yosinski/deep-visualization-toolbox#123]
Traceback (most recent call last):
  File "./run_toolbox.py", line 33, in <module>
    main()
  File "./run_toolbox.py", line 23, in main
    lv = LiveVis(settings)
  File "/home/e829/deep-visualization-toolbox/live_vis.py", line 62, in __init__
    app = app_class(settings, self.bindings)
  File "/home/e829/deep-visualization-toolbox/caffevis/app.py", line 101, in __init__
    self._populate_net_layer_info()
  File "/home/e829/deep-visualization-toolbox/caffevis/app.py", line 114, in _populate_net_layer_info
    assert len(blob_shape) in (2,4), 'Expected either 2 for FC or 4 for conv layer'
AssertionError: Expected either 2 for FC or 4 for conv layer

Who can hele me, Thank you very much!

**Comment by yosinski** [comment]
Try running with ipython --pdb to debug:

    $ ipython --pdb -- ./run_toolbox.py

Then poke around the blob and try to figure out what's going on. (Which layer does it choke on? Is that layer FC or Conv? And what shape is the blob?)
