### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by mayyphyokhaing** [yosinski/deep-visualization-toolbox#141]
When I run this ./run_toolbox.py, the following error is appeared:

Error importing settings.py. Check the error message below for more information.
If you haven't already, you'll want to copy one of the settings_local.template-*.py files
to settings_local.py and edit it to point to your caffe checkout. E.g. via:
  $ cp models/caffenet-yos/settings_local.template-caffenet-yos.py settings_local.py
  $ < edit settings_local.py >

Traceback (most recent call last):
  File "./run_toolbox.py", line 7, in <module>
    import settings
  File "/home/may/caffe/deep-visualization-toolbox/settings.py", line 218, in <module>
    if isinstance(caffevis_data_mean, basestring):
NameError: name 'basestring' is not defined

**Comment by armhzjz** [comment]
Hello mayyphyokhaing,
I am having the same problem that you reported and unfortunatelly, I haven't been able to solve it. 
Did you find a solution? If so, could you please post it here?

Thanks in advance!

**Comment by JemmyLuck** [comment]
basestring is not supported in python3,replace "basestring" with "str"
