### ISSUE TITLE
Could not open file /opt/dvtb/models/caffenet-yos/caffenet-yos-weights

### ISSUE THREAD

**Issue by hlalibe** [yosinski/deep-visualization-toolbox#150]
Really eager to run your tool on my model/data.

I installed with Docker using the link you gave: https://github.com/fishcorn/dvtb-container

When I launch the container i get this prompt: `developer@d6c8b1d52a74:/opt/dvtb$`

So then I supposed I had to run your tool with: `./run_toolbox.py`

But that gives me this error: `RuntimeError: Could not open file /opt/dvtb/models/caffenet-yos/caffenet-yos-weights`

Complete error message is:
```
got module <module 'caffevis.app' from '/opt/dvtb/caffevis/app.py'>
got app <class 'caffevis.app.CaffeVisApp'>
Got settings <module 'settings' from '/opt/dvtb/settings.py'>
/opt/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Net<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/opt/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Blob<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/opt/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Solver<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
h
CaffeVisApp mode (in main thread):     GPU
Traceback (most recent call last):
  File "./run_toolbox.py", line 33, in <module>
    main()
  File "./run_toolbox.py", line 23, in main
    lv = LiveVis(settings)
  File "/opt/dvtb/live_vis.py", line 62, in __init__
    app = app_class(settings, self.bindings)
  File "/opt/dvtb/caffevis/app.py", line 53, in __init__
    raw_scale = self._range_scale,
  File "/opt/caffe/python/caffe/classifier.py", line 26, in __init__
    caffe.Net.__init__(self, model_file, pretrained_file, caffe.TEST)
RuntimeError: Could not open file /opt/dvtb/models/caffenet-yos/caffenet-yos-weights
```

**Comment by hlalibe** [comment]
I've managed to dowload the .gz file and extract them, so i could go a bit further, the tool runs for a while then ends up with:
```
CaffeVisApp mode (in CaffeProcThread): GPU
JPGVisLoadingThread.run called
F0818 09:45:28.533731    28 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***
```
I run it in a docker container this way:
```
sudo NV_GPU=0 nvidia-docker run -ti \ 
--name dvtb \ 
-e DISPLAY \ 
-v /tmp/.X11-unix:/tmp/.X11-unix \ 
-v /path/to/a/workspace:/home/developer/work \ 
fishcorn/dvtb-container 
Then at the prompt : ./run_toolbox.py 
```
Running under Ubuntu 16.04 with Titan XP GPU card

**Comment by hlalibe** [comment]
I managed to bypass the message above by setting this line to False in opt/dvtb/settings.py
caffevis_mode_gpu = locals().get('caffevis_mode_gpu', False)

now i get to the user interface and it seems to work fine.
