### ISSUE TITLE
./run_toolbox.py  error

### ISSUE THREAD

**Issue by LRsir** [yosinski/deep-visualization-toolbox#152]
got module <module 'caffevis.app' from '/home/wzw/caffe/deep-visualization-toolbox/caffevis/app.pyc'>
got app <class 'caffevis.app.CaffeVisApp'>
Got settings <module 'settings' from '/home/wzw/caffe/deep-visualization-toolbox/settings.pyc'>
Traceback (most recent call last):
  File "./run_toolbox.py", line 33, in <module>
    main()
  File "./run_toolbox.py", line 23, in main
    lv = LiveVis(settings)
  File "/home/wzw/caffe/deep-visualization-toolbox/live_vis.py", line 62, in __init__
    app = app_class(settings, self.bindings)
  File "/home/wzw/caffe/deep-visualization-toolbox/caffevis/app.py", line 46, in __init__
    import caffe
  File "/home/wzw/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/wzw/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define init function (init_caffe)

**Comment by LiuZhe6** [comment]
I have the same problem with you , my OS is mac 10.14 Mojave

**Comment by LRsir** [comment]
@LiuZhe6 you can use pycharm to run toolbox, I had been solved this problem in 19/1/1. [my blog](https://blog.csdn.net/weixin_43991786/article/details/85559895)  I hope it can help you to solve your problem.

**Comment by LiuZhe6** [comment]
> @LiuZhe6 you can use pycharm to run toolbox, I had been solved this problem in 19/1/1. [my blog](https://blog.csdn.net/weixin_43991786/article/details/85559895) I hope it can help you to solve your problem.

Thank you so much , i will have a try!
