### ISSUE TITLE
Issue using numpy 1.10.1

### ISSUE THREAD

**Issue by clibbon** [yosinski/deep-visualization-toolbox#23]
Hi,

I have the program up and running, however there are two functions affected which both return the error
 
    TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

This occurs when attempting to access the webcam (by pressing c), which reports:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/home/alex/Programs/deep-visualization-toolbox/core.py", line 172, in run
        frame_full = read_cam_frame(self.bound_cap_device)
      File "/home/alex/Programs/deep-visualization-toolbox/image_misc.py", line 61, in read_cam_frame
        frame *= (255.0 / (frame.max() + 1e-6))
    TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

or by trying to access the list of help commands:

    Traceback (most recent call last):
      File "./run_toolbox.py", line 29, in <module>
        main()
      File "./run_toolbox.py", line 24, in main
        lv.run_loop()
      File "/home/alex/Programs/deep-visualization-toolbox/core.py", line 439, in run_loop
        self.draw_help()
      File "/home/alex/Programs/deep-visualization-toolbox/core.py", line 529, in draw_help
        self.help_buffer[:] *= .7
    TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

My google efforts have churned out this thread on inplace type castings, which behave differently in earlier python versions and wouldn't throw up this error. https://github.com/numpy/numpy/issues/6198

Have any other numpy 1.10.1 users had this problem?  

The parts I have running are amazing!

**Comment by yosinski** [comment]
Hi @clibbon, I think you're exactly right about the reason; fortunately @lionleaf has posted a solution: #21. It hasn't been merged yet (waiting until after ICLR deadline), but can you give it a try and see it it works for you?

**Comment by Deepak-** [comment]
I had the same issue, and @lionleafs solution worked!

**Comment by clibbon** [comment]
Yep, solution worked for me too. Thanks for the quick response, and the fix @lionleaf
