### ISSUE TITLE
web cam not work

### ISSUE THREAD

**Issue by nikitysh** [yosinski/deep-visualization-toolbox#30]
deepvis start and work , but if press "f" to unfreeze cam , nothing happens(but cam works fine in opencv). the same problem if press "s"   , i havent filter visualisation, only convolution.

**Comment by yosinski** [comment]
Hmmm...

What OS are you using?

What is printed in the console, if anything, when you push these keys?

If you run the test_keys.py script, what are the results?



---------------------------
Jason Yosinski, Cornell Computer Science Ph.D. candidate
http://yosinski.com/     +1.719.440.1357

**Comment by nikitysh** [comment]
using Ubuntu 14.04.3 LTS ,
when toolbox run , and press the button, prints only dots . ( key s works )
test_keys print 
Click on the picture and then carefully push the following keys:
  Press key     j:    1048682 (0x10006a) matched j
  Press key     k:    1048683 (0x10006b) matched k
  Press key     J:  (ignoring modifier leftshift)   1114186 (0x11004a) matched J
  Press key     K:  (ignoring modifier leftshift)   1114187 (0x11004b) matched K
  Press key     1:    1048625 (0x100031) matched 1
  Press key     2:    1048626 (0x100032) matched 2
  Press key  left:    1113937 (0x10ff51) matched left
  Press key right:    1113939 (0x10ff53) matched right
  Press key   esc:    1048603 (0x10001b) matched esc

I think keys right.

**Comment by nikitysh** [comment]
And I have this prints
InputImageFetcher: bind_camera starting
InputImageFetcher: capture device 0 is open
InputImageFetcher: bind_camera finished

In what key i should press for web cam?

**Comment by nikitysh** [comment]
I find problem 
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/lev/tools/caffedeep/caffe/deep-visualization-toolbox/core.py", line 172, in run
    frame_full = read_cam_frame(self.bound_cap_device)
  File "/home/lev/tools/caffedeep/caffe/deep-visualization-toolbox/image_misc.py", line 61, in read_cam_frame
    frame *= (255.0 / (frame.max() + 1e-6))
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

**Comment by yosinski** [comment]
@nikitysh Ahh, ok. This bug is related to a change in numpy 1.10 (see #18 and #21). Pull in the dev branch and it should be fixed.
