### ISSUE TITLE
Error importing settings.py.

### ISSUE THREAD

**Issue by isalirezag** [yosinski/deep-visualization-toolbox#34]
Sorry guys my question might be very stupid but I am very new.
I did all the steps carefully. I dont know what I make mistake that I receive the following error :(
I appreciate if anyone can help me out please.
Thanks in advance.

OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file -------src-dir-------/opencv-2.4.10/modules/highgui/src/window.cpp, line 483
Traceback (most recent call last):
  File "./run_toolbox.py", line 33, in <module>
    main()
  File "./run_toolbox.py", line 28, in main
    lv.run_loop()
  File "/home/alireza/caffe/deep-visualization-toolbox/live_vis.py", line 121, in run_loop
    self.init_window()
  File "/home/alireza/caffe/deep-visualization-toolbox/live_vis.py", line 84, in init_window
    cv2.namedWindow(self.window_name)
cv2.error: -------src-dir-------/opencv-2.4.10/modules/highgui/src/window.cpp:483: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

**Comment by isalirezag** [comment]
I am very new to this. sorry if my question is obvious or stupid.
I already did
$ cp models/caffenet-yos/settings_local.template-caffenet-yos.py settings_local.py
and did the change for path i.e. caffevis_caffe_root      = '/path/to/caffe'

Just to make sure, I just need to change caffevis_caffe_root    in my seetings)local.py, right?

can anyone help me out please.
Thanks in advance!
I carefully went through the steps and when I run_toolbox.py thats what I faced :/

Error importing settings.py. Check the error message below for more information.
If you haven't already, you'll want to copy one of the settings_local.template-*.py files
to settings_local.py and edit it to point to your caffe checkout. E.g. via:
  $ cp models/caffenet-yos/settings_local.template-caffenet-yos.py settings_local.py
  $ < edit settings_local.py >

Traceback (most recent call last):
File "./run_toolbox.py", line 7, in <module>
import settings
File "/home/alireza/caffe/deep-visualization-toolbox/settings.py", line 322, in <module>
raise Exception('ERROR: The given Caffe directory, %s, does not exist. Set caffevis_caffe_root in your settings_local.py to the path of your compiled Caffe checkout.' % caffevis_caffe_root)
Exception: ERROR: The given Caffe directory, /path/to/caffe, does not exist. Set caffevis_caffe_root in your settings_local.py to the path of your compiled Caffe checkout.

**Comment by isalirezag** [comment]
I fixed this by re installing the caffe and opencv and anacanda.
