### ISSUE TITLE
generating sizes larger than 227x227, error resizing mean

### ISSUE THREAD

**Issue by adamhrv** [yosinski/deep-visualization-toolbox#46]
is it possible to generate images larger than 227x227 using the optimize_image.py script?

For example, when using --data-size '(500,500)'  the script generates the error:
Traceback (most recent call last):
  File "./optimize_image.py", line 224, in <module>
    main()
  File "./optimize_image.py", line 186, in main
    raw_scale = 1.0,
  File "/root/caffe-yosinski/python/caffe/classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "/root/caffe-yosinski/python/caffe/io.py", line 258, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.

Following the suggested workaround here (http://stackoverflow.com/questions/30808735/error-when-using-classify-in-caffe) the revised code (edited in caffenet-yos/python/caffe/io.py) generates another error:

(1, 3, 227, 227)
/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py:110: UserWarning: Possible precision loss when converting from int64 to float64
  "%s to %s" % (dtypeobj_in, dtypeobj))
Traceback (most recent call last):
  File "./optimize_image.py", line 224, in <module>
    main()
  File "./optimize_image.py", line 186, in main
    raw_scale = 1.0,
  File "/root/caffe-yosinski/python/caffe/classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "/root/caffe-yosinski/python/caffe/io.py", line 264, in set_mean
    mean = resize_image(normal_mean.transpose((1,2,0)),in_shape[1:]).transpose((2,0,1)) * (m_max - m_min) + m_min
  File "/root/caffe-yosinski/python/caffe/io.py", line 332, in resize_image
    resized_std = resize(im_std, new_dims, order=interp_order)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py", line 119, in resize
    preserve_range=preserve_range)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_geometric.py", line 1296, in warp
    image = _convert_warp_input(image, preserve_range)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_geometric.py", line 1108, in _convert_warp_input
    image = img_as_float(image)
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 301, in img_as_float
    return convert(image, np.float64, force_copy)
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 241, in convert
    np.float32, np.float64))
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 114, in _dtype
    return next(dt for dt in dtypes if itemsize < np.dtype(dt).itemsize)
StopIteration

and doesn't complete the image optimization process.

Is there a way to reformat the mean file (or 3 value tuple) in your code? Or would it better to regenerate the .npy mean file for a larger size.

Thanks.

**Comment by Bato803** [comment]
I encountered a similar problem, when I tried to generate the optimization images using google-net, whose input size is (224,224), running the optimize_image.py script would give me the error:

`ValueError: Mean shape incompatible with input shape.`

At first I wondered whether it's the problem of the variable 'caffevis_data_mean' in the 'setting_local.py' file, since in the default setting the 'caffevis_data_mean' is given by 
`caffevis_data_mean = %DVT_ROOT%/models/caffenet-yos/ilsvrc_2012_mean.npy'
While in the google-net setting file it's given only by 
`caffevis_data_mean       = (104, 117, 123) `

So I generated a .npy file of google-net, but surprisingly that doesn't work as well. Same error occurs. I am still working on fixing this error, any idea?

**Comment by arikpoz** [comment]
@adamhrv
I've substantially refactored the tool, made the tool more generic and support any image size, also refactored the use of mean files to support many different input formats

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox
