### ISSUE TITLE
AttributeError: 'str' object has no attribute 'nbytes'

### ISSUE THREAD

**Issue by lukeyeager** [yosinski/deep-visualization-toolbox#5]
I noticed this in the console log after I had been playing around with the tool for a while. Not sure if it's a big issue or not.
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/lyeager/code/deep-visualization-toolbox/caffevis/app.py", line 278, in run
    self.cache.set(jpgvis_to_load_key, img_resize)
  File "/home/lyeager/code/deep-visualization-toolbox/numpy_cache.py", line 29, in set
    self._store_bytes += self._store[key].nbytes
AttributeError: 'str' object has no attribute 'nbytes'
```

**Comment by yosinski** [comment]
Good catch, thanks! Should be fixed now.
