### ISSUE TITLE
ubuntu run error

### ISSUE THREAD

**Issue by kingfengji** [yosinski/deep-visualization-toolbox#51]
Hi I've done everything as described in the instruction, but when I run the run_toolbox.py 

The last lines are like the following:
Im using ubuntu 14.04 with anaconda and all else.
Thanks!
=====================================
I0602 15:13:34.449769  5788 net.cpp:804] Ignoring source layer data
I0602 15:13:34.498936  5788 net.cpp:804] Ignoring source layer loss

Running toolbox. Push h for help or q to quit.

OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file -------src-dir-------/opencv-2.4.10/modules/highgui/src/window.cpp, line 483
Traceback (most recent call last):
  File "./run_toolbox.py", line 33, in <module>
    main()
  File "./run_toolbox.py", line 28, in main
    lv.run_loop()
  File "/home/heisenberg/Codings/deep-visualization-toolbox/live_vis.py", line 121, in run_loop
    self.init_window()
  File "/home/heisenberg/Codings/deep-visualization-toolbox/live_vis.py", line 84, in init_window
    cv2.namedWindow(self.window_name)
cv2.error: -------src-dir-------/opencv-2.4.10/modules/highgui/src/window.cpp:483: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

**Comment by kingfengji** [comment]
PS: I have the libgtk2.0-dev and pkg-config stuffs,

**Comment by kingfengji** [comment]
yeah problem solved. install an older version of opencv and compile the caffe without gpu will do.
