### ISSUE TITLE
Unable to run the toolbox with modified GoogleNet

### ISSUE THREAD

**Issue by BBAUniversity** [yosinski/deep-visualization-toolbox#64]
I have tried successfully the scripts (**run_toolbox.py** and **optimize_image.py**) with my modified version of AlexNet. But when I have tried with my version of GoogleNet I haves this Errors:
 **run_toolbox.py**:
ERROR: required bindings (backward_from_layer) not found! Try using the deconv-deep-vis-toolbox branch as described here: https://github.com/yosinski/deep-visualization-toolbox
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/deep/deep-visualization-toolbox/caffevis/caffe_proc_thread.py", line 96, in run
    self.net.backward_from_layer(backprop_layer, diffs, zero_higher = True)
AttributeError: 'Classifier' object has no attribute 'backward_from_layer'

**optimize_image.py**: ( with -- push-layer "loss3/classifierM") M for my modification of layer:

File "./optimize_image.py", line 225, in <module>
    main()
  File "./optimize_image.py", line 187, in main
    raw_scale = 1.0,
  File "/home/deep/Downloads/caffe-master/python/caffe/classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "/home/deep/Downloads/caffe-master/python/caffe/io.py", line 259, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.

**Comment by arikpoz** [comment]
@BBAUniversity 
I've made the tool substantially more generic: all the hardcoded parts where replaced with new settings parameters, most are deduced automatically by analyzing the network definition file
Specifically, I've tested it on GoogleNet and it works well, I've also refactored the use of mean files to support many different input formats

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox
