### ISSUE TITLE
Problem of (GoogleNet) with deconf and ./optimize_image.py

### ISSUE THREAD

**Issue by BBAUniversity** [yosinski/deep-visualization-toolbox#66]
I have tried GoogleNet default model of deep-visualization-toolbox. Deconf dont work and the result of this commande:
./optimize_image.py --push-layer 'loss3/classifier' --push-channel 0 --decay 0.0001 --blur-radius 1.0 --blur-every 4 --max-iter 6000 --lr-policy constant --lr-params "{'lr': 100.0}

Give the the Error:

Traceback (most recent call last):
  File "./optimize_image.py", line 225, in <module>
    main()
  File "./optimize_image.py", line 187, in main
    raw_scale = 1.0,
  File "/home/deep/Downloads/caffe-master/python/caffe/classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "/home/deep/Downloads/caffe-master/python/caffe/io.py", line 259, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.

**Comment by evangello** [comment]
Hello,
I have the same problem. Did you manage to solve this issue?

**Comment by heitorrapela** [comment]
"File "/home/deep/Downloads/caffe-master/python/caffe/io.py", line 259, in set_mean
raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape."

Try to use --data-size "(224,224)", and checkout this [link](https://stackoverflow.com/questions/30808735/error-when-using-classify-in-caffe)

./optimize_image.py --push-layer pool5/7x7_s1 --decay 0.0001 --blur-radius 1.0 --blur-every 4 --max-iter 5 --lr-policy constant --lr-params "{'lr': 100.0}" --data-size "(224,224)"
