### ISSUE TITLE
How to produce optimized images for two output labels dataset?

### ISSUE THREAD

**Issue by taylorty** [yosinski/deep-visualization-toolbox#68]
First thank you for making this amazing toolbox.
My problem is that when I tried to generate optimized images, I got index out of range error. I think it is because I only have two output labels for my training dataset instead of 2000+ labels in the case of ImageNet

Traceback (most recent call last):
  File "optimize_image.py", line 225, in <module>
    main()
  File "optimize_image.py", line 220, in main
    brave = args.brave, skipbig = args.skipbig)
  File "/Users/Documents/caffe/deep-visualization-toolbox/optimize/gradient_optimizer.py", line 177, in run_optimize
    xx, results = self._optimize(params, x0)
  File "/Users/Documents/caffe/deep-visualization-toolbox/optimize/gradient_optimizer.py", line 229, in _optimize
    push_label = self.labels[params.push_unit[0]]
IndexError: list index out of range

**Comment by abaybektursun** [comment]
Yep, getting the same error. I have only 2 classes too

**Comment by arikpoz** [comment]
@taylorty, @abaybektursun 
I've made the tool substantially more generic: all the hardcoded parts where replaced with new settings parameters, most are deduced automatically by analyzing the network definition file
I suggest you recheck using the updated version of the tool

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox
