### ISSUE TITLE
Support for more network types.

### ISSUE THREAD

**Issue by dtmoodie** [yosinski/deep-visualization-toolbox#81]
Hello,
I've been working with SSD (https://github.com/weiliu89/caffe/tree/ssd) and I would like to visualize the output with your toolkit.
Currently I'd be happy with just getting a visualization of the low level activations and the fully convolutional section of the network.
However I'm running into an issue in caffevis/app.py:115 because some of the layers have a 3 dimensional shape.  How necessary is this assertion?  What changes should be made to support or ignore 3 dimensional operations?

**Comment by Solomon1588** [comment]
> How necessary is this assertion? What changes should be made to support or ignore 3 dimensional operations?
When I visualize the SSD model，I have the same question, i.e.  caffevis/app.py:115  assert len(blob_shape) in (2,4), but the 'conv4_3_norm_mbox_priorbox' layer's blob shape is (1,2,17328).
In addidation,I have another error as follow:
CaffeProcThread.run called
CaffeVisApp mode (in CaffeProcThread): GPU
 JPGVisLoadingThread.run called
Traceback (most recent call last):
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/run_toolbox.py", line 33, in <module>
    main()
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/run_toolbox.py", line 28, in main
    lv.run_loop()
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/live_vis.py", line 220, in run_loop
    imshow_needed |= app.draw(self.panes)
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/caffevis/app.py", line 211, in draw
    self._draw_aux_pane(panes['caffevis_aux'], layer_data_3D_highres)
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/caffevis/app.py", line 480, in _draw_aux_pane
    self._draw_prob_labels_pane(pane)
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/caffevis/app.py", line 241, in **_draw_prob_labels_pane
    probs_flat = self.net.blobs[self.settings.caffevis_prob_layer].data.flatten()
KeyError: 'prob'**
Could you give me some information?
Thanks a lot :D

**Comment by Solomon1588** [comment]
<font size = 4>How necessary is this assertion? What changes should be made to support or ignore 3 dimensional operations?
When I visualize the SSD model，I have the same question, i.e. caffevis/app.py:115 assert len(blob_shape) in (2,4), but the 'conv4_3_norm_mbox_priorbox' layer's blob shape is (1,2,17328).
In addidation,I have another error as follow:
<font size = 3>CaffeProcThread.run called
CaffeVisApp mode (in CaffeProcThread): GPU
JPGVisLoadingThread.run called
Traceback (most recent call last):
File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/run_toolbox.py", line 33, in 
main()
File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/run_toolbox.py", line 28, in main
lv.run_loop()
File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/live_vis.py", line 220, in run_loop
imshow_needed |= app.draw(self.panes)
File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/caffevis/app.py", line 211, in draw
self._draw_aux_pane(panes['caffevis_aux'], layer_data_3D_highres)
File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/caffevis/app.py", line 480, in _draw_aux_pane
self._draw_prob_labels_pane(pane)
File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox/caffevis/app.py", line 241, in _draw_prob_labels_pane
**<font color = red>probs_flat = self.net.blobs[self.settings.caffevis_prob_layer].data.flatten()
KeyError: 'prob'**
Could you give me some information?
Thanks a lot :D

**Comment by chunxuxiao** [comment]
@dtmoodie 
I just meet this problem today.
![screenshot from 2017-01-05 20-37-02](https://cloud.githubusercontent.com/assets/6430027/21680777/d111671e-d386-11e6-8e4e-d4bef38b3668.png)

Here is what i have done for new type:
I know it it not the right way to solve this problem, but for the temporary, I have no time to spend on this problem.
![screenshot from 2017-01-05 20-30-30](https://cloud.githubusercontent.com/assets/6430027/21680631/e8261c8e-d385-11e6-8078-2b742307010c.png)
![screenshot from 2017-01-05 20-30-54](https://cloud.githubusercontent.com/assets/6430027/21680633/ed8a118a-d385-11e6-930b-ef5d31eb7cd0.png)
Hope to help you!

**Comment by Bardo91** [comment]
Hi @chunxuxiao, would you mind to tell which files are those that you modified? Thank you very much!

**Comment by chunxuxiao** [comment]
@Bardo91 As you can see in the line 116 of the second snapshot the assert will failed, for that the length of blob is not equal to 2 or 4 when "key =conv_4_3_norm_mbox_priorbox (As shown in the first snapshot )", I just common that 'assert' and add line 117, 118 in the py file that caused break down of the running, in another file(the third snapshot ), I add line 253 and 254 in the for loop. I'am not sure if the visualization is ritht, and  sorry for forgetting  the concretes name of  the files, I have graduate in school and not doing that field anymore. Hope that will help you!

**Comment by arikpoz** [comment]
@dtmoodie, @chunxuxiao, @Bardo91
I've made the tool substantially more generic: all the hardcoded parts where replaced with new settings parameters, most are deduced automatically by analyzing the network definition file

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox

**Comment by shonehang** [comment]
@arikpoz I want to know how to use your tool for SSD, just change the deploy prototxt and caffemodel?Thank you!!!
