### ISSUE TITLE
ERROR: required bindings (backward_from_layer) not found!

### ISSUE THREAD

**Issue by Solomon1588** [yosinski/deep-visualization-toolbox#88]
> ERROR: required bindings (backward_from_layer) not found! Try using the deconv-deep-vis-toolbox branch as described here: https://github.com/yosinski/deep-visualization-toolbox
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/wjq/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/wjq/ObejctDetection/project/deep-visualization-toolbox-2/caffevis/caffe_proc_thread.py", line 96, in run
    self.net.backward_from_layer(backprop_layer, diffs, zero_higher = True)
AttributeError: 'Classifier' object has no attribute 'backward_from_layer'

As the forementioned information，I encounter the error‘(backward_from_layer) not found’，and it suggest using the right branch，though I follow the instructions（download the deep-visualization-toolbox,switch the author‘s caffe brance，etc.）.
So I need someone to help me solve this problem。
Thanks a lot :D

**Comment by Napcatola** [comment]
I encounter the same error.Have you got any solutions to this problem?

**Comment by BrotherJing** [comment]
If you have installed another version of caffe before, you may need to change the PYTHONPATH environment variable to the pycaffe directory under this branch.

**Comment by FredaZhang338** [comment]
@Solomon1588 Hello~I encounter the same error,Have you solved this problem?
@BrotherJing Excuse me, can you give a full explanation of changing the PYTHONPATH?? I compiled the caffe and under the caffe dirctory, I followed the Step 1(Compile the deconv-deep-vis-toolbox branch of caffe) to compile again.Then I git clone the toolbox. But I got the same error. Can you help me to fix it?

**Comment by liangpu597** [comment]
I encounter the same error. can you tell me the solution?
@BrotherJing
